#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'OpenMDAO interface to NASA HEC systems at Ames Research Center.',
 'download_url': '',
 'entry_points': '',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'nas_access',
 'package_data': {'nas_access': []},
 'package_dir': {'': 'src'},
 'packages': ['nas_access'],
 'url': '',
 'version': '0.3',
 'zip_safe': False}


setup(**kwargs)

